import type {
  GetPayrollRowsParams,
  PayrollFilterOptionsResponse,
  PayrollManagementRow,
  PayrollManagementStoredRow,
} from "./types"

export const MOCK_NETWORK_DELAY_MS = 400

export async function delayMockRequest(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms))
}

function money(n: number): string {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 })
}

/**
 * Ten March bi-weekly rows for FY 2023–24 (`fy-2024`): one paycheck per listed employee
 * plus a second March period for Minh Nguyen and Anika Patel. Matches default Payroll Details
 * (Bi Weekly, FY 2023–24, March, All departments) so Get returns a full table.
 */
const STORED_ROWS: PayrollManagementStoredRow[] = [
  {
    employeeId: "E1001",
    employeeLastName: "Nguyen",
    employeeFirstName: "Minh",
    employeeMiddleName: "T",
    suffix: "",
    department: "Human Resources",
    bargainingUnit: "BU-01",
    type: "Exempt",
    position: "HR Analyst",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(412.5),
    pers: money(620.0),
    defComp: money(150.0),
    cafeteria: money(45.0),
    lifeInsurance: money(12.5),
    standby: money(0),
    spa: money(75.0),
    cellStipend: money(50.0),
    std: money(0),
    ot: money(220.0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(5200.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-hr",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1001",
  },
  {
    employeeId: "E1002",
    employeeLastName: "Patel",
    employeeFirstName: "Anika",
    employeeMiddleName: "",
    suffix: "",
    department: "Information Technology",
    bargainingUnit: "BU-02",
    type: "Exempt",
    position: "Software Engineer",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(520.75),
    pers: money(780.25),
    defComp: money(200.0),
    cafeteria: money(45.0),
    lifeInsurance: money(18.0),
    standby: money(100.0),
    spa: money(0),
    cellStipend: money(75.0),
    std: money(0),
    ot: money(0),
    recruitingIncentive: money(500.0),
    cashOut: money(0),
    payout: money(0),
    salary: money(7800.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-it",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1002",
  },
  {
    employeeId: "E1003",
    employeeLastName: "Garcia",
    employeeFirstName: "Luis",
    employeeMiddleName: "A",
    suffix: "Jr",
    department: "Public Works",
    bargainingUnit: "BU-03",
    type: "Non-Exempt",
    position: "Equipment Operator",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(298.4),
    pers: money(410.1),
    defComp: money(0),
    cafeteria: money(30.0),
    lifeInsurance: money(9.25),
    standby: money(0),
    spa: money(0),
    cellStipend: money(25.0),
    std: money(120.0),
    ot: money(340.5),
    recruitingIncentive: money(0),
    cashOut: money(50.0),
    payout: money(0),
    salary: money(3850.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-pw",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1003",
  },
  {
    employeeId: "E1004",
    employeeLastName: "Chen",
    employeeFirstName: "Wei",
    employeeMiddleName: "",
    suffix: "",
    department: "Finance",
    bargainingUnit: "BU-01",
    type: "Exempt",
    position: "Accountant",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(380.0),
    pers: money(560.0),
    defComp: money(175.0),
    cafeteria: money(45.0),
    lifeInsurance: money(14.0),
    standby: money(0),
    spa: money(0),
    cellStipend: money(0),
    std: money(0),
    ot: money(0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(200.0),
    salary: money(6100.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-fin",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1004",
  },
  {
    employeeId: "E1005",
    employeeLastName: "Okafor",
    employeeFirstName: "Chioma",
    employeeMiddleName: "N",
    suffix: "",
    department: "Human Resources",
    bargainingUnit: "BU-01",
    type: "Exempt",
    position: "Benefits Specialist",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(355.2),
    pers: money(502.8),
    defComp: money(125.0),
    cafeteria: money(45.0),
    lifeInsurance: money(11.0),
    standby: money(0),
    spa: money(40.0),
    cellStipend: money(50.0),
    std: money(0),
    ot: money(80.0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(4950.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-hr",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1005",
  },
  {
    employeeId: "E1006",
    employeeLastName: "Martinez",
    employeeFirstName: "Sofia",
    employeeMiddleName: "R",
    suffix: "",
    department: "Information Technology",
    bargainingUnit: "BU-02",
    type: "Exempt",
    position: "IT Manager",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(610.0),
    pers: money(890.0),
    defComp: money(320.0),
    cafeteria: money(45.0),
    lifeInsurance: money(22.0),
    standby: money(0),
    spa: money(0),
    cellStipend: money(75.0),
    std: money(0),
    ot: money(0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(9200.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-it",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1006",
  },
  {
    employeeId: "E1007",
    employeeLastName: "Johnson",
    employeeFirstName: "Marcus",
    employeeMiddleName: "",
    suffix: "",
    department: "Public Works",
    bargainingUnit: "BU-03",
    type: "Non-Exempt",
    position: "Foreman",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(265.1),
    pers: money(355.9),
    defComp: money(50.0),
    cafeteria: money(30.0),
    lifeInsurance: money(8.5),
    standby: money(60.0),
    spa: money(0),
    cellStipend: money(25.0),
    std: money(0),
    ot: money(410.0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(4200.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-pw",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1007",
  },
  {
    employeeId: "E1008",
    employeeLastName: "Ibrahim",
    employeeFirstName: "Fatima",
    employeeMiddleName: "K",
    suffix: "",
    department: "Finance",
    bargainingUnit: "BU-01",
    type: "Exempt",
    position: "Payroll Technician",
    payPeriodBegin: "2024-03-01",
    payPeriodEnd: "2024-03-15",
    checkDate: "2024-03-20",
    fica: money(310.0),
    pers: money(455.0),
    defComp: money(100.0),
    cafeteria: money(45.0),
    lifeInsurance: money(12.0),
    standby: money(0),
    spa: money(20.0),
    cellStipend: money(0),
    std: money(0),
    ot: money(95.0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(5100.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-fin",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1008",
  },
  {
    employeeId: "E1001",
    employeeLastName: "Nguyen",
    employeeFirstName: "Minh",
    employeeMiddleName: "T",
    suffix: "",
    department: "Human Resources",
    bargainingUnit: "BU-01",
    type: "Exempt",
    position: "HR Analyst",
    payPeriodBegin: "2024-03-16",
    payPeriodEnd: "2024-03-31",
    checkDate: "2024-04-05",
    fica: money(405.0),
    pers: money(612.0),
    defComp: money(150.0),
    cafeteria: money(45.0),
    lifeInsurance: money(12.5),
    standby: money(0),
    spa: money(75.0),
    cellStipend: money(50.0),
    std: money(0),
    ot: money(180.0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(5200.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-hr",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1001",
  },
  {
    employeeId: "E1002",
    employeeLastName: "Patel",
    employeeFirstName: "Anika",
    employeeMiddleName: "",
    suffix: "",
    department: "Information Technology",
    bargainingUnit: "BU-02",
    type: "Exempt",
    position: "Software Engineer",
    payPeriodBegin: "2024-03-16",
    payPeriodEnd: "2024-03-31",
    checkDate: "2024-04-05",
    fica: money(518.0),
    pers: money(772.0),
    defComp: money(200.0),
    cafeteria: money(45.0),
    lifeInsurance: money(18.0),
    standby: money(80.0),
    spa: money(0),
    cellStipend: money(75.0),
    std: money(0),
    ot: money(0),
    recruitingIncentive: money(0),
    cashOut: money(0),
    payout: money(0),
    salary: money(7800.0),
    filterFiscalYearId: "fy-2024",
    filterMonthOrQuarterId: "m-03",
    filterDepartmentId: "dept-it",
    filterPayrollType: "bi_weekly",
    filterEmployeeId: "E1002",
  },
]

function toPublicRow(row: PayrollManagementStoredRow): PayrollManagementRow {
  return {
    employeeId: row.employeeId,
    employeeLastName: row.employeeLastName,
    employeeFirstName: row.employeeFirstName,
    employeeMiddleName: row.employeeMiddleName,
    suffix: row.suffix,
    department: row.department,
    bargainingUnit: row.bargainingUnit,
    type: row.type,
    position: row.position,
    payPeriodBegin: row.payPeriodBegin,
    payPeriodEnd: row.payPeriodEnd,
    checkDate: row.checkDate,
    fica: row.fica,
    pers: row.pers,
    defComp: row.defComp,
    cafeteria: row.cafeteria,
    lifeInsurance: row.lifeInsurance,
    standby: row.standby,
    spa: row.spa,
    cellStipend: row.cellStipend,
    std: row.std,
    ot: row.ot,
    recruitingIncentive: row.recruitingIncentive,
    cashOut: row.cashOut,
    payout: row.payout,
    salary: row.salary,
  }
}

export async function fetchPayrollFilterOptionsMock(): Promise<PayrollFilterOptionsResponse> {
  if (import.meta.env.DEV) await delayMockRequest(MOCK_NETWORK_DELAY_MS)
  const fiscalYears: PayrollFilterOptionsResponse["fiscalYears"] = [
    { value: "fy-2024", label: "FY 2023–24" },
    { value: "fy-2025", label: "FY 2024–25" },
  ]
  const monthOptions: PayrollFilterOptionsResponse["monthOptions"] = [
    { value: "m-01", label: "January" },
    { value: "m-02", label: "February" },
    { value: "m-03", label: "March" },
    { value: "m-04", label: "April" },
    { value: "m-05", label: "May" },
    { value: "m-06", label: "June" },
    { value: "m-07", label: "July" },
    { value: "m-08", label: "August" },
    { value: "m-09", label: "September" },
    { value: "m-10", label: "October" },
    { value: "m-11", label: "November" },
    { value: "m-12", label: "December" },
  ]
  const quarterOptions: PayrollFilterOptionsResponse["quarterOptions"] = [
    { value: "q-1", label: "Q1" },
    { value: "q-2", label: "Q2" },
    { value: "q-3", label: "Q3" },
    { value: "q-4", label: "Q4" },
  ]
  const departments: PayrollFilterOptionsResponse["departments"] = [
    { value: "all", label: "All departments" },
    { value: "dept-hr", label: "Human Resources" },
    { value: "dept-it", label: "Information Technology" },
    { value: "dept-pw", label: "Public Works" },
    { value: "dept-fin", label: "Finance" },
  ]
  const employeeMap = new Map<string, string>()
  for (const r of STORED_ROWS) {
    if (!employeeMap.has(r.filterEmployeeId)) {
      employeeMap.set(
        r.filterEmployeeId,
        `${r.employeeFirstName} ${r.employeeLastName}`.trim(),
      )
    }
  }
  const employees: PayrollFilterOptionsResponse["employees"] = Array.from(employeeMap.entries())
    .sort((a, b) => a[1].localeCompare(b[1], undefined, { sensitivity: "base" }))
    .map(([value, label]) => ({ value, label }))
  return { fiscalYears, monthOptions, quarterOptions, departments, employees }
}

function matchesDepartment(row: PayrollManagementStoredRow, departmentId: string): boolean {
  if (departmentId === "all") return true
  return row.filterDepartmentId === departmentId
}

function matchesEmployees(row: PayrollManagementStoredRow, employeeIds: readonly string[]): boolean {
  if (employeeIds.length === 0) return true
  return employeeIds.includes(row.filterEmployeeId)
}

export async function fetchPayrollRowsMock(params: GetPayrollRowsParams): Promise<PayrollManagementRow[]> {
  if (import.meta.env.DEV) await delayMockRequest(MOCK_NETWORK_DELAY_MS)
  const filtered = STORED_ROWS.filter(
    (row) =>
      row.filterPayrollType === params.payrollType &&
      row.filterFiscalYearId === params.fiscalYearId &&
      row.filterMonthOrQuarterId === params.monthOrQuarterId &&
      matchesDepartment(row, params.departmentId) &&
      matchesEmployees(row, params.employeeIds),
  )
  return filtered.map(toPublicRow)
}

export const PAYROLL_TABLE_TEMPLATE_HEADERS: readonly string[] = [
  "Employee ID",
  "Employee Last Name",
  "Employee First Name",
  "Employee Middle Name",
  "Suffix",
  "Department",
  "Bargaining Unit",
  "Type",
  "Position",
  "Pay Period Begin",
  "Pay Period End",
  "Check Date",
  "FICA",
  "PERS",
  "Def Comp",
  "Cafeteria",
  "Life Insurance",
  "Standby",
  "SPA",
  "Cell Stipend",
  "STD",
  "OT",
  "Recruiting Incentive",
  "Cash Out",
  "Payout",
  "Salary",
] as const
