export const PAYROLL_TABLE_TEMPLATE_HEADERS: readonly string[] = [
  "Employee ID",
  "First Name",
  "Middle Name",
  "Last Name",
  "Suffix",
  "Department",
  "Bargaining Unit",
  "Type",
  "Position",
  "Pay Period Begin",
  "Pay Period End",
  "Check Date",
  "FICA",
  "PERS",
  "Def Comp",
  "Cafeteria",
  "Life Insurance",
  "Standby",
  "SPA",
  "Cell Stipend",
  "STD",
  "OT",
  "Recruiting Incentive",
  "Cash Out",
  "Payout",
  "Salary",
  "Year",
  "Month",
  "Payroll Type",
] as const
