import type { UserModuleRow } from "./types"

export const MOCK_NETWORK_DELAY_MS = 500

export function delay(ms: number): Promise<void> {
  return new Promise((resolve) => {
    window.setTimeout(resolve, ms)
  })
}

export const mockSeedRows: UserModuleRow[] = [
  { id: "1", employeeNo: "1", firstName: "Bennett", lastName: "Leyla", employee: "Bennett Leyla", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "bennett.leyla", password: "Password1-2", active: true },
  { id: "2", employeeNo: "2", firstName: "CAVILLO-HEFNER", lastName: "KRISTEN", employee: "CAVILLO-HEFNER KRISTEN", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "cavillo-hefner.kristen", password: "Password1-2", active: true },
  { id: "3", employeeNo: "3", firstName: "Hanion", lastName: "Teal", employee: "Hanion Teal", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "hanion.teal", password: "Password1-2", active: true },
  { id: "4", employeeNo: "4", firstName: "MacKay", lastName: "Jessica", employee: "MacKay Jessica", department: "Public Health", roleAssignments: ["Department Admin", "Time Study Admin", "Time Study Supervisor", "User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "mackay.jessica", password: "Password1-2", active: true },
  { id: "5", employeeNo: "5", firstName: "Osguera", lastName: "Lenis", employee: "Osguera Lenis", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "osguera.lenis", password: "Password1-2", active: true },
  { id: "6", employeeNo: "6", firstName: "Prater", lastName: "Jordan", employee: "Prater Jordan", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "prater.jordan", password: "Password1-2", active: true },
  { id: "7", employeeNo: "7", firstName: "RAKESTRAW", lastName: "MELISSA", employee: "RAKESTRAW MELISSA", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "rakestraw.melissa", password: "Password1-2", active: true },
  { id: "8", employeeNo: "8", firstName: "Rugeger", lastName: "Natalie", employee: "Rugeger Natalie", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "rugeger.natalie", password: "Password1-2", active: true },
  { id: "9", employeeNo: "9", firstName: "Smith", lastName: "Shonda", employee: "Smith Shonda", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: true, assignedMultiCodes: "MAA", jobClassification: "NA", loginId: "smith.shonda", password: "Password1-2", active: true },
  { id: "10", employeeNo: "10", firstName: "Taylor", lastName: "Sarah", employee: "Taylor Sarah", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rubens Patrick", supervisorSecondary: "Rugeger Natalie", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "taylor.sarah", password: "Password1-2", active: true },
  { id: "11", employeeNo: "11", firstName: "Andrews", lastName: "Lia", employee: "Andrews Lia", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "andrews.lia", password: "Password1-2", active: true },
  { id: "12", employeeNo: "12", firstName: "James", lastName: "Peter", employee: "James Peter", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "james.peter", password: "Password1-2", active: true },
  { id: "13", employeeNo: "13", firstName: "Arman", lastName: "Jude", employee: "Arman Jude", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "arman.jude", password: "Password1-2", active: true },
  { id: "14", employeeNo: "14", firstName: "Stewart", lastName: "Dax", employee: "Stewart Dax", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "stewart.dax", password: "Password1-2", active: true },
  { id: "15", employeeNo: "15", firstName: "Cohen", lastName: "Lea", employee: "Cohen Lea", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "cohen.lea", password: "Password1-2", active: true },
  { id: "16", employeeNo: "16", firstName: "Fox", lastName: "Amy", employee: "Fox Amy", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "fox.amy", password: "Password1-2", active: true },
  { id: "17", employeeNo: "17", firstName: "Hart", lastName: "Eli", employee: "Hart Eli", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "hart.eli", password: "Password1-2", active: true },
  { id: "18", employeeNo: "18", firstName: "Ivy", lastName: "Noor", employee: "Ivy Noor", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "ivy.noor", password: "Password1-2", active: true },
  { id: "19", employeeNo: "19", firstName: "Khan", lastName: "Omar", employee: "Khan Omar", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "khan.omar", password: "Password1-2", active: true },
  { id: "20", employeeNo: "20", firstName: "Lane", lastName: "Rose", employee: "Lane Rose", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "lane.rose", password: "Password1-2", active: true },
  { id: "21", employeeNo: "21", firstName: "Moore", lastName: "Zion", employee: "Moore Zion", department: "Public Health", roleAssignments: ["User"], supervisorPrimary: "Rugeger Natalie", supervisorSecondary: "Rubens Patrick", spmp: false, tsMinDay: "480", programs: true, activities: true, supervisorApportioning: false, multicodesEnabled: false, assignedMultiCodes: "", jobClassification: "NA", loginId: "moore.zion", password: "Password1-2", active: true },
]

export const mockUserRows: UserModuleRow[] = [...mockSeedRows]

export function filterRows(rows: UserModuleRow[], inactiveOnly: boolean): UserModuleRow[] {
  if (inactiveOnly) {
    return rows.filter((row) => !row.active)
  }

  return rows
}
